run:
  timeout: 3m

linters:
  disable-all: true
  enable-all: false
  enable:
    - deadcode
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    # we would like to add these
    # - dupl
    # - staticcheck

linters-settings:
  gofmt:
    simplify: true
  govet:
    # we would like to enable this eventually
    check-shadowing: false
  maligned:
    suggest-new: true
  misspell:
    locale: US

issues:
  max-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: internal/pkg/util/fs/overlay/
      linters:
        - misspell

    - path: internal/pkg/util/user/cgo_lookup_unix.go
      linters:
        - deadcode
