bootstrap: library
from: centos:7

%labels
    maintainer "Eduardo Arango<eduardo@sylabs.io>"

%help
    export BAD_GUY=Thanos
    export SMART_GUY=tony

%environment
    GOPATH=/go
    PATH=$PATH:$GOPATH/bin:/usr/local/go/bin
    CGO_ENABLED=0
    AVENGERS=asemble
    export GOPATH PATH CGO_ENABLED AVENGERS

%setup
    echo "SETUP"

%appenv testapp
    TESTAPP=testapp
    export TESTAPP

%appinstall testapp
    echo 'echo $TESTAPP' > $SINGULARITY_APPROOT/bin/testapp.sh
    chmod 0755 $SINGULARITY_APPROOT/bin/testapp.sh

%apprun testapp
    $TESTAPP.sh

%appinstall foo

    echo "INSTALLING FOO"
    touch filefoo.exec

%appinstall bar

    echo "INSTALLING BAR"
    touch filebar.exec

%apphelp foo
This is the help for foo!

%applabels foo
HELLOTHISIS foo

%applabels bar
HELLOTHISIS bar

%appenv foo
HELLOTHISIS=foo
export HELLOTHISIS

%apprun foo
    echo "RUNNING FOO"

%startscript
    if [ ! -z "$1" ]; then
        exec python /echo.py 2>$1
    fi

%runscript
    echo "Running command: $*"
    exec "$@"

%post
    # required to build sandbox image from the SIF generated image
    chmod 0755 /
    echo "POST"
    # Needed for startscript
    yum install -y hostname

    cat > /echo.py <<-EOF
import sys
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s.bind(('', 0))
s.listen(1)

# write port to stderr
sys.stderr.write("%d\n" % s.getsockname()[1])
sys.stderr.flush()

conn, addr = s.accept()
data = conn.recv(1024)
conn.sendall(data)
conn.close()
EOF

%test
    exec "$@"
