bootstrap: library
from: centos:7

%labels
    maintainer "Eduardo Arango<eduardo@sylabs.io>"

%help
    export BAD_GUY=Thanos
    export SMART_GUY=tony

%environment
    GOPATH=/go
    PATH=$PATH:$GOPATH/bin:/usr/local/go/bin
    CGO_ENABLED=0
    AVENGERS=asemble
    export GOPATH PATH CGO_ENABLED AVENGERS

%setup
    echo "SETUP"

%appenv testapp
    TESTAPP=testapp
    export TESTAPP

%appinstall testapp
    echo 'echo $TESTAPP' > $SINGULARITY_APPROOT/bin/testapp.sh
    chmod 0755 $SINGULARITY_APPROOT/bin/testapp.sh

%apprun testapp
    $TESTAPP.sh

%appinstall foo

    echo "INSTALLING FOO"
    touch filefoo.exec

%appinstall bar

    echo "INSTALLING BAR"
    touch filebar.exec

%apphelp foo
This is the help for foo!

%applabels foo
HELLOTHISIS foo

%applabels bar
HELLOTHISIS bar

%appenv foo
HELLOTHISIS=foo
export HELLOTHISIS

%apprun foo
    echo "RUNNING FOO"

%startscript
    exec nc -l -k -p $1 -e /bin/cat 2>/dev/null

%runscript
    echo "Running command: $*"
    exec "$@"

%post
    echo "POST"
    # Needed for startscript
    yum install -y nmap-ncat hostname

%test
    exec "$@"
