Bootstrap: self
Exclude: /var/lib/docker /home/vanessa /opt/* /var/backups /var/tmp /var/singularity/mnt

%runscript
    echo "This is what happens when you run the container..."

%post
    echo "Hello from inside the container"
