#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPSPEC" ]; then
    message 0 "ERROR: SAPP specfile not given\n"
    exit 1
fi

if [ -z "$SAPPFILE" ]; then
    message 0 "ERROR: SAPP output file not passed\n"
    exit 1
fi

if [ -z "$INSTALLDIR" ]; then
    message 0 "ERROR: INSTALLDIR not given\n"
    exit 1
fi


message 1 "Checking paths...\n"
if [ ! -d "$INSTALLDIR" ]; then
    if ! mkdir -p "$INSTALLDIR" 2>/dev/null; then
        message 0 "ERROR: Could not create temporary directory\n";
        exit 1
    fi
fi

message 1 "Checking writable...\n"
if ! touch "$SAPPFILE" 2>/dev/null; then
    message 0 "ERROR: Could not create $SAPPFILE\n"
    exit 1
fi



exit 0
