#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPSPEC" ]; then
    message 0 "ERROR: SAPP specfile not given\n"
    exit 1
fi

if [ -z "$SAPPFILE" ]; then
    message 0 "ERROR: SAPP output file not passed\n"
    exit 1
fi

if [ -z "$INSTALLDIR" ]; then
    message 0 "ERROR: INSTALLDIR not given\n"
    exit 1
fi

if [ ! -d "$INSTALLDIR/c" ]; then
    message 0 "ERROR: INSTALLROOT ($INSTALLDIR/c) not present\n"
    exit 1
fi

INSTALLROOT="$INSTALLDIR/c"
DESTDIR="$INSTALLDIR/c"
export INSTALLROOT DESTDIR

message 1 "Running prep scriptlet\n"
( get_section_from_conf "prep" "$SAPPSPEC" || exit 1 ) | (cd "$INSTALLROOT"; /bin/sh -x)
if [ "$?" != "0" ]; then
    message 0 "ERROR: 'prep' scriptlet exited non-zero\n"
    exit 1
fi
message 1 "Running build scriptlet\n"
( get_section_from_conf "build" "$SAPPSPEC" || exit 1 ) | (cd "$INSTALLROOT"; /bin/sh -x)
if [ "$?" != "0" ]; then
    message 0 "ERROR: 'build' scriptlet exited non-zero\n"
    exit 1
fi


exit 0
