#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPSPEC" ]; then
    message 0 "ERROR: SAPP specfile not given\n"
    exit 1
fi

if [ -z "$SAPPDIR" ]; then
    message 0 "ERROR: SAPPDIR not given\n"
    exit 1
fi

if [ ! -x "$libexecdir/singularity/sexec" ]; then
    message 0 "ERROR: Sexec not found\n"
    exit 1
fi



# Set the necessary bits for sexec and the singularity driver to run
SAPPCONTAINER="$SAPPDIR/c"
SINGULARITY_COMMAND="test"
export SAPPCONTAINER SINGULARITY_COMMAND

message 1 "Running %test...\n"
exec "$libexecdir/singularity/sexec" "$@"

# Should never get here
exit 0
