#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPSPEC" ]; then
    message 0 "ERROR: SAPP specfile not given\n"
    exit 1
fi

if [ -z "$INSTALLDIR" ]; then
    message 0 "ERROR: INSTALLDIR not given\n"
    exit 1
fi



# Pull in the %files section of the spec
message 1 "Evaluating: packages\n"
get_section_from_conf "packages" $SAPPSPEC | while read pkg; do
    if [ -z "$pkg" ]; then
        continue
    fi
    if [ -x "/usr/bin/rpm" ]; then
        if rpm -q "$pkg" >/dev/null 2>&1; then
            rpm -ql "$pkg" | while read i; do
                if ! /bin/sh -c "$libexecdir/singularity/mods/install_file $i"; then
                    message 0 "Error: failed processing file: $i\n"
                    exit 1
                fi
            done
        else
            message 0 "Package is not installed: $pkg\n"
        fi
    elif [ -x "/usr/bin/dpkg" ]; then
        message 0 "ERROR: We don't support dpkg yet... Coming soon!\n"
        exit 1
    fi
done
if [ "$?" -ne "0" ]; then
    exit 1
fi

exit 0
