#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPSPEC" ]; then
    message 0 "ERROR: SAPP specfile not given\n"
    exit 1
fi

if [ -z "$INSTALLDIR" ]; then
    message 0 "ERROR: INSTALLDIR not given\n"
    exit 1
fi


LIB_SEARCH_PATH=`cd "$INSTALLDIR/c"; find . -name "lib*.so*" -type f | xargs -n 1 dirname 2>/dev/null | sort | uniq | sed -e 's/^\.//' | tr '\n' ':'`
PYTHONHOME=`cd "$INSTALLDIR/c"; find . \( -perm -0100 -or -perm -0010 -or -perm -0001 \) -name python -print | sed -e 's/^\.//' | sed -e 's/\/bin\/python$//'`

echo "declare -x PATH=/bin:/usr/bin:/sbin:/usr/sbin" >> "$INSTALLDIR/c/singularity.env"
echo "declare -x LANG=C" >> "$INSTALLDIR/c/singularity.env"
echo "declare -x PS1=\"singularity.\$SAPPNAME> \"" >> "$INSTALLDIR/c/singularity.env"

if [ -n "$LIB_SEARCH_PATH" ]; then
    echo "declare -x LD_LIBRARY_PATH=\"\$LD_LIBRARY_PATH:$LIB_SEARCH_PATH\"" >> "$INSTALLDIR/c/singularity.env"
fi

if [ -n "$PYTHONHOME" ]; then
    echo "declare -x PYTHONHOME=\"$PYTHONHOME\"" >> "$INSTALLDIR/c/singularity.env"
fi




exit 0
