#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPSPEC" ]; then
    message 0 "ERROR: SAPP specfile not given\n"
    exit 1
fi

if [ -z "$SAPPDIR" ]; then
    message 0 "ERROR: SAPPDIR not given\n"
    exit 1
fi



if [ ! -d "$SAPPDIR/c" ]; then
    if ! mkdir -p "$SAPPDIR/c" 2>/dev/null; then
        message 0 "ERROR: Could not container directory $SAPPDIR/c\n";
        exit 1
    fi
fi


# Things we always just must have
message 1 "Evaluating: hard requirements\n"
for i in /bin/sh; do
    if ! copy_file_to_sappdir "$i"; then
        message 0 "Error: failed processing requires: $i\n"
        exit 1
    fi
done
if [ "$?" -ne "0" ]; then
    exit 1
fi

# Pull in defined keys that specify files
message 1 "Evaluating: Exec\n"
for i in `get_key_from_conf "exec" $SAPPSPEC`; do
    if FULLFILE=`which "$i" 2>/dev/null`; then
        copy_file_to_sappdir "$FULLFILE"
    else
        message 0 "Error: failed processing program: $i\n"
        exit 1
    fi
done
if [ "$?" -ne "0" ]; then
    exit 1
fi

# Pull in the %files section of the spec
message 1 "Evaluating: %files\n"
get_section_from_conf "files" $SAPPSPEC | while read file dir; do
    if [ -n "$file" ]; then
        if ! copy_file_to_sappdir "$file" "$dir"; then
            message 0 "Error: failed processing file: $a\n"
            exit 1
        fi
    fi
done
if [ "$?" -ne "0" ]; then
    exit 1
fi

exit 0
