#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPSPEC" ]; then
    message 0 "SAPP specfile not given\n"
    exit 1
fi

if [ -z "$SAPPDIR" ]; then
    message 0 "SAPPDIR not given\n"
    exit 1
fi


message 1 "Invoking dependency check\n";
while true; do
    UPDATED=0
    for i in $libexecdir/singularity/mods/deps/*; do
        if [ -x "$i" ]; then
            message 3 "Executing: $i\n"
            sh "$i" "$@"
            RET=$?
            if [ "$RET" -eq "0" ]; then
                UPDATED=1
            elif [ "$RET" -eq "1" ]; then
                # no new deps
                true
            else
                # ERROR
                message 0 "ERROR: Dependency resolution threw an error!\n"
                exit 1
            fi
        fi
    done
    if [ "$UPDATED" -eq "0" ]; then
        break
    fi
done

exit 0
