#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$INSTALLDIR" ]; then
    message 0 "ERROR: INSTALLDIR not given\n"
    exit 1
fi


trap exit KILL INT QUIT


run_resolver() {
    TYPE="$1"
    shift
    for i in $libexecdir/singularity/mods/deps/${TYPE}_*.dep; do
        if [ -x "$i" ]; then
            if ! /bin/sh -c "$i $@"; then
                message 0 "ERROR: failed resolving dependencies on: $*\n"
            fi
        fi
    done
}


dep_resolver() {
    if [ -f "$1" ]; then
        if [ -x "$1" ]; then
            run_resolver exe "$1"
        fi
        run_resolver reg "$1"
    fi
}

file="$1"
dir="$2"

if [ -f "$INSTALLDIR/c/$file" ]; then
    exit 0
fi

if [ -e "$file" ]; then
    filename=`basename "$file"`
    if [ -z "$dir" ]; then
        dir=`dirname "$file"`
    fi
    if [ ! -d "$INSTALLDIR/c/$dir" ]; then
        mkdir -p "$INSTALLDIR/c/$dir"
    fi

    message 1 "Installing file: $dir/$filename\n"
    if ! /bin/cp -arpL "$file" "$INSTALLDIR/c/$dir/"; then
        message 0 "ERROR: Could not copy file to container: $file\n"
        exit 1
    fi
    if ! dep_resolver "$dir/$filename"; then
        message 0 "ERROR: Could not resolve dependencies for: $file\n"
        exit 1
    fi
else
    message 0 "ERROR: File not found: $file\n"
    exit 1
fi

exit 0
