#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPSPEC" ]; then
    message 0 "ERROR: SAPP specfile not given\n"
    exit 1
fi

if [ -z "$INSTALLDIR" ]; then
    message 0 "ERROR: INSTALLDIR not given\n"
    exit 1
fi


message 1 "Checking for files that need santizing\n"

if [ -f "$INSTALLDIR/c/etc/passwd" ]; then
    message 1 "Found /etc/passwd in container, sanitizing it...\n"
    while read line; do
        ID=`echo "$line" | awk -F: '{print $3}'`
        if [ "$ID" -le 500 ]; then
            echo $line
        fi
    done < "$INSTALLDIR/c/etc/passwd" > "$INSTALLDIR/c/etc/passwd.1"
    cat "$INSTALLDIR/c/etc/passwd.1" > "$INSTALLDIR/c/etc/passwd"
    rm -f "$INSTALLDIR/c/etc/passwd.1"
fi

if [ -f "$INSTALLDIR/c/etc/group" ]; then
    message 1 "Found /etc/group in container, sanitizing it...\n"
    while read line; do
        ID=`echo "$line" | awk -F: '{print $3}'`
        if [ "$ID" -le 500 ]; then
            echo $line
        fi
    done < "$INSTALLDIR/c/etc/group" > "$INSTALLDIR/c/etc/group.1"
    cat "$INSTALLDIR/c/etc/group.1" > "$INSTALLDIR/c/etc/group"
    rm -f "$INSTALLDIR/c/etc/group.1"
fi

if [ -f "$INSTALLDIR/c/etc/shadow" ]; then
    message 1 "Found /etc/shadow in container, sanitizing it...\n"
    cat /dev/null > "$INSTALLDIR/c/etc/shadow"
fi


# TODO: Make this configurable
LOCALE_ARCHIVE=`find $INSTALLDIR/c -type f -name "locale-archive"`
if [ -n "$LOCALE_ARCHIVE" ]; then
    message 1 "Found locale-archive, removing...\n"
    rm -f $LOCALE_ARCHIVE
fi


exit 0
