#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPSPEC" ]; then
    message 0 "ERROR: SAPP specfile not given\n"
    exit 1
fi

if [ -z "$SAPPDIR" ]; then
    message 0 "ERROR: SAPPDIR not given\n"
    exit 1
fi


message 1 "Including SAPPFILE\n"
cat "$SAPPSPEC" > "$SAPPDIR/spec"

message 1 "Calculating container size\n"
du -sk "$SAPPDIR/c" | cut -f 1 > "$SAPPDIR/size"

message 1 "Calculating checksums\n"
(cd "$SAPPDIR/c"; find . -type f | xargs md5sum) > "$SAPPDIR/files"


exit 0
