#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPFILE" ]; then
    message 0 "ERROR: SAPP output file not passwed\n"
    exit 1
fi

if [ -z "$INSTALLDIR" ]; then
    message 0 "ERROR: INSTALLDIR not given\n"
    exit 1
fi


# These get added by Sexec during the %test
message 1 "Cleaning up unpackaged files\n"
rm -f $INSTALLDIR/c/dev/*

message 1 "Creating output SAPP container\n"
echo "#!/usr/bin/env sapprun" > $SAPPFILE
echo "Name: $NAME" >> $SAPPFILE
echo "Summary: $SUMMARY" >> $SAPPFILE
echo "$HEADER_END" >> $SAPPFILE


(cd "$INSTALLDIR"; find . | cpio -o --quiet -H newc ) | gzip -c9 >> "$SAPPFILE"
message 1 "WROTE: $SAPPFILE\n"

chmod +x "$SAPPFILE"

exit 0
