#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPDIR" ]; then
    message 0 "ERROR: SAPPDIR not given\n"
    exit 1
fi

if [ ! -d "$SAPPDIR/c" ]; then
    message 0 "ERROR: SAPP directory not found\n"
    exit 1
fi

if [ ! -f "$SAPPDIR/files" ]; then
    message 0 "ERROR: File checksums not found for this SAPP\n"
    exit 1
fi

cd "$SAPPDIR/c" 2>/dev/null
if [ "$?" -ne "0" ]; then
    message 0 "ERROR: Could not chdir to SAPP directory\n"
    exit 1
fi

if ! md5sum -c "$SAPPDIR/files"; then
    message 0 "ERROR: Cached file check failed, something has changed!\n\n"
    message 0 "Try deleting the container, and reinstalling it:\n"
    message 0 "    $ singularity delete $SAPPNAME\n";
    message 0 "    $ singularity install $SAPPNAME.sapp\n\n";
    exit 1
fi

exit 0
