#!/bin/sh -
# Copyright (c) 2016-2018, Yannick Cote <yanick@divyan.org>. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be found
# in the LICENSE file.
set -e

# defaults and compiler options
prefix="/usr/local"
# exec_prefix will be set again later
exec_prefix=""
verbose=0
debug=0
hstcc=
hstcc_opts="cc gcc clang i686-w64-mingw32-gcc x86_64-w64-mingw32-gcc"
hstcxx=
hstcxx_opts="c++ g++ clang++ i686-w64-mingw32-g++ x86_64-w64-mingw32-g++"
tgtcc=
tgtcc_opts=$hstcc_opts
tgtcxx=
tgtcxx_opts=$hstcxx_opts
hststatic=0
tgtstatic=0
package_version=""



usage () {
	echo "${0##*/}: could not complete configuration"
}

usage_args () {
	echo "Usage: ${0##*/}: [-dvsS] [-p prefix] [-e exec_prefix] [-b builddir] [-c hstcc]"
	echo "                 [-C tgtcc] [-V version] [-x hstcxx] [-X tgtcxx]"
	echo "       -v build project with verbose flags on"
	echo "       -d build project with debug flags on"
	echo "       -s build final host project binary statically"
	echo "       -S build final target project binary statically"
	echo "       -p install project in \`prefix'"
	echo "       -e install project executables in \`exec_prefix'"
	echo "       -b build project in \`builddir'"
	echo "       -c build project with host C \`compiler'"
	echo "       -C build project with target C\`compiler'"
	echo "       -V build project with given version"
	echo "       -x build project with host C++ \`compiler'"
	echo "       -h this help"
	echo "\`host C compiler': $hstcc_opts"
	echo "\`host C++ compiler': $hstcxx_opts"
	echo "\`target C compiler': $tgtcc_opts"
}

# save the command line
cmdline="`readlink -f $0` $*"

# check line options
args=`getopt p:e:b:c:C:dsSvV:x:h $*`
if [ $? -ne 0 ]; then
	usage_args
	exit 2
fi
eval set -- "$args"
while [ $# -ne 0 ]; do
 case $1 in
  -p) prefix="$2"; shift; shift;;
  -e) exec_prefix="$2"; shift; shift;;
  -b) builddir="$2"; shift; shift;;
  -c) hstcc="$2"; shift; shift;;
  -C) tgtcc="$2"; shift; shift;;
  -x) hstcxx="$2"; shift; shift;;
  -d) debug=1; shift;;
  -s) hststatic=1; shift;;
  -S) tgtstatic=1; shift;;
  -v) verbose=1; shift;;
  -V) package_version="$2"; shift; shift;;
  -h) usage_args; exit 2;;
  --) shift; break;;
  ?) usage_args
     exit 2;;
 esac
done
#
# non-option param
if [ $# != 0 ]; then
	usage_args
	exit 2
fi
if [ -z "$exec_prefix" ]; then
    exec_prefix=$prefix
fi
topdir=`dirname \`readlink mconfig\`` || (echo "\`mconfig' needs to be symlinked at the top of the project."; exit 2)
sourcedir=`readlink -f .`
mfragsdir=$sourcedir/mlocal/frags
mchecksdir=$sourcedir/mlocal/checks

if [ -z "$package_version" ]; then
    package_version=`git describe --match 'v[0-9]*' --dirty --always | sed -e "s/^v//;s/-/_/g;s/_/-/;s/_/./g"`
fi
# export so this can be used in mlocal/checks
export package_version


#######################################################################
# System build tool configuration and debug/verbose flags 
#######################################################################
if [ -f $mchecksdir/basechecks.chk ]; then
	echo "=> running base system checks ..."
	. $mchecksdir/basechecks.chk
else
	echo "error: file $mchecksdir/basechecks.chk needs to be present"
	exit 2
fi



#######################################################################
# Extra user specified system configuration checks (mlocal/checks)
#######################################################################
# write a "#define" definition entry into $builddir/config.h
config_add_def ()
{
	if [ "$1" = "" -o "$2" = "" ]; then
		return
	fi
	echo "#define $*" >> $builddir/config.h
}

rm -rf $builddir/config.h
if [ -f $mchecksdir/project.chk ]; then
	echo "=> running project specific checks ..."
	. $mchecksdir/project.chk
fi



#######################################################################
# Generated fragments
#######################################################################
echo "=> generating fragments ..."
if [ ! -d $mfragsdir ]; then
	echo "error: $mfragsdir should be populated with Makefile fragments."
	echo "NOTE: Fragments may be copied from examples found in $topdir/examples/<project>/* "
	echo "NOTE: to $sourcedir/mlocal/* and tweak for your project."
	exit 2
fi


########################
# verbosity
########################
if [ "$verbose" = 1 ]; then
	echo "# build with verbose flag on" >> $genmk
	echo "V :=" >> $genmk
else
	echo "# silent build" >> $genmk
	echo "V := @" >> $genmk
fi
echo >> $genmk


########################
# build tools
########################
cat >> $genmk << EOF
# source/build locations
BUILDDIR := .
SOURCEDIR := $sourcedir
CONTRIBDIR := $contribdir
PREFIX := $prefix
EXEC_PREFIX := $exec_prefix

HOSTAR := ar
HOSTCC := $hstcc
HOSTCXX := $hstcxx
HOSTLD := $hstcc
HOSTRANLIB := ranlib
HOSTSIZE := size
HOSTOBJCOPY := objcopy

AR := `readlink -f \`which \\\`$tgtcc -print-prog-name=ar\\\`\``
CC := $tgtcc
CXX := $tgtcxx
LD := `readlink -f \`which \\\`$tgtcc -print-prog-name=ld\\\`\``
RANLIB := `readlink -f \`which \\\`$tgtcc -print-prog-name=ranlib\\\`\``
SIZE := size
OBJCOPY := `readlink -f \`which \\\`$tgtcc -print-prog-name=objcopy\\\`\``

ARCH := $tgt_arch

EOF


########################
# modules
########################
:>$genconfdir/module.lst

found_modules=`(cat modules | awk '{ printf("%s ", $0) }') \
		2>/dev/null || true`
if [ "$found_modules" = "" ]; then
	found_modules=`find . -name '*.mconf' -print`
	if [ "$found_modules" = "" ]; then
		echo "error: no build modules found !"
		echo
		echo "You need to at least create one \`<module_name>.mconf' "
		echo "file describing either a program, a lib, or a set of"
		echo "objects to build."
		exit 2
	fi
fi
echo " found build modules:"
echo "CPPFLAGS :=" >> $genmk
# NOTE: parsed module (*.mconf) files only substitute var tgt_arch for now
for m in $found_modules; do
	mod=`eval echo ${m##*./}`
	modpath=`eval echo ${mod%/*}`
	if [ `readlink -f "$modpath"` = `readlink -f "."` ]; then
		modpath="."
	fi
	if [ ! -f $mod ]; then
		echo "error: module file \`$mod' not found!"
		exit 2
	fi

	echo "   +-> $mod"
	echo "$modpath `eval basename $mod`" >> $genconfdir/module.lst
	mkdir -p $genconfdir/$modpath
	cat $mod | awk -v tgt_arch=$tgt_arch '{ gsub(/tgt_arch/, \
				tgt_arch); print }' > $genconfdir/${mod}.parsed
#	echo "CPPFLAGS += -iquote\$(SOURCEDIR)/$modpath" >> $genmk
done
echo >> $genmk

# init LDFLAGS if static builds are supported
if [ "$hststatic" = "1" -a "$tgtstatic" = "1" ]; then
	echo "LDFLAGS := -static" >> $genmk
else
	echo "LDFLAGS :=" >> $genmk
fi
echo >> $genmk

cat >> $genmk << EOF
# make sure \`all' is the first rule
all:
EOF


# call genmod.awk, generating Makefile components
$topdir/genmod.awk modfile=$genconfdir/module.lst \
	topdir=$sourcedir \
	host=$host \
	verbose=$verbose \
	debug=$debug \
	genconfdir=$genconfdir \
	tmpldir=$topdir/tmpl



#######################################################################
# Target Makefile
#######################################################################
drawline () {
	echo >> $output
	printf "# [ Embedding file : %50s ] #\n" $1 >> $output
	echo >> $output
}

echo "=> building Makefile ..."

:> $output
echo "#" >> $output
echo "# Non-recursive Makefile GENERATED by \`${0##*/}' -- `date`" >> $output
echo "# configured: $cmdline" >> $output
echo "#" >> $output

drawline $genmk
cat $genmk >> $output

drawline $mfragsdir/common_opts.mk
cat $mfragsdir/common_opts.mk >> $output

if [ "$debug" != 1 ]; then
	drawline $mfragsdir/release_opts.mk
	cat $mfragsdir/release_opts.mk >> $output
else
	drawline $mfragsdir/debug_opts.mk
	cat $mfragsdir/debug_opts.mk >> $output
fi

if [ -f "$mfragsdir/arch_${tgt_arch}_opts.mk" ]; then
	drawline $mfragsdir/arch_${tgt_arch}_opts.mk
	cat $mfragsdir/arch_${tgt_arch}_opts.mk >> $output
fi

drawline $genconfdir/modules.mk
cat $genconfdir/modules.mk >> $output

drawline $genconfdir/all.mk
cat $genconfdir/all.mk >> $output

drawline $mfragsdir/Makefile.stub
# here, `depends' need to happen after all other rules; at the very end
final_all=`cat $genconfdir/all.mk | awk 'BEGIN { FS="all: " } { print $2 }'`
cat $mfragsdir/Makefile.stub | awk \
	"{ gsub(/^collect:/, \"collect: $final_all\"); print }" >> $output


rm -rf $genconfdir



#######################################################################
# Target package build files
#######################################################################

TARGET=dist/rpm/singularity.spec
echo "=> generating $TARGET ..."
rm -f $TARGET
VERSION="`echo "$package_version"|sed 's/-.*//'`"
RELEASE="`echo "$package_version"|sed 's/[^-]*-//'`"
sed "s/@PACKAGE_VERSION@/$VERSION/;s/@PACKAGE_RELEASE@/$RELEASE/" $TARGET.in >$TARGET


#######################################################################
# Configuration results
#######################################################################
echo "=> project setup with :"
echo "    - target arch: $tgt_arch"
echo "    - target compiler: $tgtcc"
echo "    - host wordsize: ${wordsize}-bit"
echo "    - host system: $host"
if [ "$verbose" = 1 ]; then
	echo "    - verbose: yes"
else
	echo "    - verbose: no"
fi
if [ "$debug" = 1 ]; then
	echo "    - debug: yes"
else
	echo "    - debug: no"
fi

echo "=> $builddir/Makefile ready, try:"
echo "   $ cd $builddir"
echo "   $ make"
