bootstrap: docker
from: sylabsio/golang:1.11-stretch

%post
    echo "Set up sudo & circleci user [uid=1000][g=sudo]"
    apt-get install sudo
    useradd -u 1001 -g sudo circleci

# Expects /sroot to exist and /go/src/github.com/sylabs/singularity to exist from bind mounts
%runscript
    echo "Running go1.11-stretch test suite"
    cd /go/src/github.com/sylabs/singularity
    make -C builddir/ test

