#!/bin/sh

# We run assuming app folder is PWD

for script in /.singularity.d/env/*.sh; do
    if [ -f "$script" ]; then
        . "$script"
    fi
done

# If it exists, source app environment
if [ -f "scif/environment" ]; then
    . "scif/environment"
fi
exec "$@"
