#!/bin/sh

for script in /.singularity.d/env/*.sh; do
    if [ -f "$script" ]; then
        . "$script"
    fi
done

if test -n "${SINGULARITY_APPNAME:-}"; then
    if [ -f "/scif/apps/${SINGULARITY_APPNAME:-}/scif/01-base.sh" ]; then
        . "/scif/apps/${SINGULARITY_APPNAME:-}/scif/01-base.sh"
    fi
    if [ -f "/scif/apps/${SINGULARITY_APPNAME:-}/scif/90-environment.sh" ]; then
        . "/scif/apps/${SINGULARITY_APPNAME:-}/scif/90-environment.sh"
    fi
fi

exec "$@"
