#!/bin/sh

for script in /.singularity.d/env/*.sh; do
    if [ -f "$script" ]; then
        . $script
    fi
done

if test -x /.singularity.d/runscript; then
    exec /.singularity.d/runscript "$@"
else
    echo "No Singularity runscript found, executing /bin/sh"
    exec /bin/sh "$@"
fi
