#!/bin/sh

for script in /.singularity/env/*.sh; do
    if [ -f "$script" ]; then
        . $script
    fi
done

if test -x /.singularity/runscript; then
    exec /.singularity/runscript "$@"
else
    echo "No Singularity runscript found, executing /bin/sh"
    exec /bin/sh "$@"
fi
