#!/bin/sh

for script in /singularity.d/env/*.sh; do
    if [ -f "$script" ]; then
        . $script
    fi
done

if test -n "$SHELL" ; then
    exec $SHELL "$@"

    echo "ERROR: Failed running shell as defined by 'SINGULARITY_SHELL'" 1>&2
    exit 1
fi

if test -x /bin/sh; then
    SHELL=/bin/sh
    export SHELL
    exec /bin/sh "$@"
else
    echo "ERROR: /bin/sh does not exist in container" 1>&2
fi
exit 1
