#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPFILE" ]; then
    message 0 "SAPP output file not passed\n"
    exit 1
fi

if [ -z "$SAPPDIR" ]; then
    message 0 "SAPPDIR not given\n"
    exit 1
fi


FILES="/etc/resolv.conf
       /proc/cpuinfo
       /proc/meminfo"


for f in $FILES; do
    if [ -f "$SAPPDIR/c/$f" ]; then
        message 2 "Not creating file, already exists: $f\n"
    else
        BASEDIR=`dirname "$f"`
        if [ ! -d "$SAPPDIR/c/$BASEDIR" ]; then
            mkdir -p "$SAPPDIR/c/$BASEDIR"
        fi
        cp -rap "$f" "$SAPPDIR/c/$f"
    fi
done

exit 0
