#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPFILE" ]; then
    message 1 "SAPP output file not passed"
    exit 1
fi

if [ -z "$SAPPDIR" ]; then
    message 1 "SAPPDIR not given"
    exit 1
fi


if [ -x "$libexecdir/singularity/sexec" ]; then
    message 2 "Exec'ing Sexec"
    exec $libexecdir/singularity/sexec "$@"
fi

exit 0
