#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi


cleanup() {
    BAIL_OUT=1
}

trap cleanup SIGHUP SIGINT SIGTERM

SAPPFILE="$1"
SAPPCACHE="$HOME/.sapp-cache"
SAPPDIR=""
RETVAL=0
SAPPNAME=`echo $SAPPFILE | sed -e 's@.sapp$@@'`
export SAPPFILE SAPPCACHE SAPPDIR RETVAL SAPPNAME
shift

if [ -z "$SAPPFILE" ]; then
    message 0 "USAGE: singularity (options) run [SAPP File] (SAPP options)\n"
    exit 1
fi

if [ ! -f "$SAPPFILE" ]; then
    message 0 "SAPP file ($SAPPFILE) not found\n"
    exit 1
fi

if [ ! -d "$SAPPCACHE" ]; then
    mkdir -p "$SAPPCACHE"
fi


message 2 "Running '$SAPPFILE'\n"

if ! CHECKSUM=`md5sum "$SAPPFILE" | awk '{print $1}'`; then
    message 0 "ERROR: Could not obtain checksum of $SAPPFILE\n"
    exit 1
fi

SAPPDIR="$SAPPCACHE/$SAPPNAME/$CHECKSUM"

if [ ! -d "$SAPPDIR" ]; then
    if ! mkdir -p "$SAPPDIR"; then
        message 0 "ERROR: Could not create working directory at $SAPPDIR\n"
        exit 1
    fi
fi

message 2 "Working directory: $SAPPDIR\n"


for i in $libexecdir/singularity/run/[0-9]*; do
    if [ -f "$i" ]; then
        message 3 "Running: $i\n"
        sh "$i" "$@"
        EXITCODE="$?"
        if [ "$EXITCODE" -ne "0" ]; then
            message 1 "Error thrown from module: $i\n"
            message 2 "Left tmpdir at $TMPDIR\n"
            exit $EXITCODE
        fi
    else
        message 1 "Error locating module: $i\n"
        message 2 "Left tmpdir at $TMPDIR\n"
        exit 1
    fi
done

if [ -n "$BAIL_OUT" ]; then
    exit 1
fi


if [ -x "$libexecdir/singularity/sexec" ]; then
    message 2 "Exec'ing Sexec\n"
    SAPPCONTAINER="$SAPPDIR/c"
    export SAPPCONTAINER
    exec "$libexecdir/singularity/sexec" "$@"
fi

# we should never get here
exit 255
