BootStrap: busybox
MirrorURL: https://www.busybox.net/downloads/binaries/1.26.2-defconfig-multiarch/busybox-x86_64

%post
    echo "Hello from inside the container"

%runscript
    echo "Running command: $*"
    exec "$@"

%appenv testapp
    TESTAPP=testapp
    export TESTAPP

%appinstall testapp
    echo 'echo $TESTAPP' > $SINGULARITY_APPROOT/bin/testapp.sh
    chmod 0755 $SINGULARITY_APPROOT/bin/testapp.sh

%apprun testapp
    $TESTAPP.sh
