#!/usr/bin/env bash

# man 1 bash
set -o errexit # set -e
set -o nounset # set -u
set -o pipefail
set -x

sw_vers
command -v singularity
singularity help
singularity version

singularity search alpine
singularity pull library://library/default/alpine:latest && [[ -f alpine_latest.sif ]]
singularity pull docker://busybox:latest && [[ -f busybox_latest.sif ]]
