#!/bin/bash -ex

export OS_TYPE="$1"
export OS_VERSION="$2"
export SINGULARITY_E2E="true"

case $OS_TYPE in
    centos|opensuse) .travis/rpmbuild_test ;;
    debian) .travis/debuild_test ;;
    *) echo "$OS_TYPE" not supported; exit 1 ;;
esac
