#!/bin/bash -ex

# this script runs as root under docker 

OS_VERSION="$1"

# Prepare for build
export DEBIAN_FRONTEND=noninteractive
export LC_ALL=C
apt-get update
apt-get -y dist-upgrade
apt-get -y install devscripts build-essential lintian gdebi-core git

DEB_VERS=$(LC_ALL=C dpkg-parsechangelog | grep '^Version:' | cut -d ' ' -f 2,2)
PLAIN_VERS=$(echo ${DEB_VERS} | sed 's#-.*##')
git archive --format=tar HEAD | gzip > ../singularity-container_${PLAIN_VERS}.orig.tar.gz

# Install dependencies
mk-build-deps
mv singularity-container-build-deps_*.deb ..
gdebi -n ../singularity-container-build-deps_*.deb

# Clean up directory
make maintainer-clean

# Build package
debuild -us -uc

echo "Directory containing the build .deb-files:"
ls -la ..
gdebi -n ../singularity-container_*.deb

# Install python 3 and pylint
apt-get -y install python3 python3-pip python3-setuptools
apt-get -y install pylint

# Install docker
apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable"
apt-get update
apt-get -y install docker-ce

# run the test suite
apt-get -y install libtool sudo e2fsprogs
sed -i 's,^prefix=.*,prefix=/usr,' test.sh
sed -i 's,^sysconfdir=.*,sysconfdir=/etc,' test.sh
sed -i 's,^localstatedir=.*,localstatedir=/var,' test.sh
useradd --create-home testuser
echo "Defaults:testuser env_keep=DOCKER_HOST" >>/etc/sudoers
echo "testuser ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers

# build image for isolated builds
sed -i 's,^prefix=.*,prefix=/usr,' secbuildimg.sh
sed -i 's,^sysconfdir=.*,sysconfdir=/etc,' secbuildimg.sh
sed -i 's,^localstatedir=.*,localstatedir=/var,' secbuildimg.sh
make secbuildimg

su testuser -c "make test"
