#!/bin/bash -ex

./autogen.sh

# Test that distclean target works fine:
./configure --prefix=/usr/local
make distclean

./configure --prefix=/usr/local
sudo make install
sudo make secbuildimg
make test
