#!/bin/bash -ex

# this script runs as root under docker 
# OS_VERSION is in $1

# build and install
yum install -y libtool rpm-build make
./autogen.sh
./configure
make dist
rpmbuild -ta *.tar.gz
rpm -iv ~/rpmbuild/RPMS/*/*.rpm

# run the test suite
yum install -y libtool sudo which e2fsprogs
sed -i 's,^prefix=.*,prefix=/usr,' test.sh
sed -i 's,^sysconfdir=.*,sysconfdir=/etc,' test.sh
sed -i 's,^localstatedir=.*,localstatedir=/var,' test.sh
useradd testuser
echo "testuser ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers
su testuser -c "make test"
