#!/bin/bash -ex

# this script runs as root under docker

deps_file=".travis/deps/${OS_TYPE}_deps"

if [[ -e "${deps_file}" ]]; then
    source "${deps_file}"
else
    echo "${OS_TYPE} not supported yet, please create ${deps_file}!"
    exit 1
fi

# build and install
install_autogen_deps
./autogen.sh

install_configure_deps
./configure
make dist
rpmbuild -ta *.tar.gz

install_rpms

if [ "$OS_VERSION" = 6 ]; then
    echo "the python tests have not yet been ported to centos6 python, and will be skipped."
fi

install_test_deps

# run the test suite
sed -i 's,^prefix=.*,prefix=/usr,' test.sh
sed -i 's,^sysconfdir=.*,sysconfdir=/etc,' test.sh
sed -i 's,^localstatedir=.*,localstatedir=/var,' test.sh
useradd -u 1000 testuser
echo "Defaults:testuser env_keep=DOCKER_HOST" >>/etc/sudoers
echo "testuser ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers
su testuser -c "make test"
