#!/bin/bash -ex

case $OS_TYPE in
    "") .travis/install_test ;;
    macos) .travis/macos_build && .travis/macos_test ;;
    centos|debian|opensuse) .travis/docker_run ;;
    *) echo "Unknown OS_TYPE $OS_TYPE"; exit 1;;
esac
