#!/bin/sh

HEADER_END="SINGULARITY_END_HEADER"
export HEADER_END


if [ -z "$MESSAGELEVEL" ]; then
    /bin/echo "Warning: MESSAGELEVEL is undefined, temporarily setting to '5' (all messages)"
    MESSAGELEVEL=5
fi



GRAY=`tput dim`
RED=`tput setaf 1`
GREEN=`tput setaf 2`
YELLOW=`tput setaf 3`
BLUE=`tput setaf 4`
PINK=`tput setaf 5`
CYAN=`tput setaf 6`
WHITE=`tput setaf 7`
NORMAL=`tput sgr0`


message() {
    LEVEL=$1
    if [ "$LEVEL" -eq "0" ]; then
        /bin/echo -ne "${RED}$2${NORMAL}" 1>&2
    elif [ "$LEVEL" -le "$MESSAGELEVEL" ]; then
        if [ "$LEVEL" -eq "1" ]; then
            /bin/echo -ne "${NORMAL}$2${NORMAL}"
        else
            /bin/echo -ne "${GRAY}$2${NORMAL}"
        fi
    fi
    return
}


get_key_from_conf() {
    KEY="$1"
    FILE="$2"
    if OUTPUT=`grep -i "^$KEY: " $FILE`; then
        /bin/echo "$OUTPUT" | sed -e "s@^$KEY: @@i"
        return 0
    fi
    return 1
}

get_section_from_conf() {
    SECTION="$1"
    FILE="$2"
    TOGGLE=""
    cat $FILE | while read line; do
        if [ -n "$TOGGLE" ]; then
            if /bin/echo "$line" | grep -q "^%"; then
                # we are done...
                return 0
            fi
            /bin/echo "$line"
        else
            if /bin/echo "$line" | grep -q "%$SECTION"; then
                TOGGLE=1
            fi
        fi
    done

    return 0
}

copy_file_to_sappdir() {
    file="$1"
    targetdir="$2"
    sappdir="$SAPPDIR/c"
    RETVAL=0

    if [ -z "$SAPPDIR" ]; then
        message 0 "ERROR: SAPPDIR not defined\n"
        exit 1
    fi

    if [ -z "$file" ]; then
        message 0 "ERROR: called copy_file_to_sappdir with no file\n"
        return 0
    fi

    if [ -z "$targetdir" ]; then
        targetdir=`dirname "$file"`
    fi

    if [ ! -d "$sappdir/$targetdir" ]; then
        message 4 "Creating target dir:   $targetdir\n"
        mkdir -p "$sappdir/$targetdir"
    fi
    if [ -f "$sappdir/$file" ]; then
        message 2 "File already included: $file\n"
    elif [ -e "$file" ]; then
        message 1 "Installing file: $file\n"
        cp -rL "$file" "$sappdir/$targetdir" 2>&1
        RETVAL="$?"
    else
        message 0 "Could not find file: $file\n"
        return 1
    fi
    return $RETVAL
}

check_pattern() {
    STRING=$1
    PATTERN=$2
    case "$PATTERN" in
        $STRING)
            true
        ;;
        *)
            return 1
        ;;
    esac
    return 0
}

cmd() {
    MSG=`/bin/echo "$*" | cut -c 1-68`
    message 5 " + $MSG"
    "$@" >/dev/null 2>&1
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        message 5 "\\033[77G${GREEN}OK${NORMAL}\n"
    else
        message 5 "\\033[74G${RED}ERROR${NORMAL}\n"
    fi
    return $RETVAL
}


run_module() {
    MODULE="$1"
    RETVAL=255
    if [ -x "$libexecdir/singularity/mods/$MODULE" ]; then
        message 3 "Running module: $MODULE\n"
        sh "$libexecdir/singularity/mods/$MODULE"
        RETVAL=$?
    else
        message 0 "ERROR: Unknown module: $MODULE\n"
    fi
    return $RETVAL
}
