#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPSPEC" ]; then
    message 1 "SAPP specfile not given"
    exit 1
fi

if [ -z "$TMPDIR" ]; then
    message 1 "TMPDIR not given"
    exit 1
fi



message 2 "Searching for library dependencies"
find $TMPDIR -type f -executable -print | while read file; do
    message 5 "scanning executable file for dependencies: $file"
    ldd $file | sed -e 's@ @\n@g' | while read dep; do
        if [ -f "$dep" ]; then
            BASENAME=`basename $dep`
            message 3 "found dependency:      $dep"
            if [ ! -d "$TMPDIR/lib$LIBSUFFIX" ]; then
                mkdir -p "$TMPDIR/lib$LIBSUFFIX"
            fi
            if [ ! -f "$TMPDIR/lib$LIBSUFFIX/$BASENAME" ]; then
                message 2 "copying dependency:    $dep"
                cp -L "$dep" "$TMPDIR/lib$LIBSUFFIX/$BASENAME"
            fi
        fi
    done
done

exit 0
