#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPSPEC" ]; then
    message 1 "SAPP specfile not given\n"
    exit 1
fi

if [ -z "$TMPDIR" ]; then
    message 1 "TMPDIR not given\n"
    exit 1
fi

INCLUDE_LIBS="/lib64/libnss_files.so.2 /lib/libnss_files.so.2 /lib64/libnss_dns.so.2 /lib/libnss_dns.so.2 /lib64/libresolv.so.2 /lib/libresolv.so.2"

# '1' is the return value if nothing gets updated, so if we update anything
# we set this to '0'
RETVAL=1

LIBSUFFIX=`uname -m | grep -q "x86_64" && echo "64"`
LIBDIR="$TMPDIR/c/lib$LIBSUFFIX"
if [ ! -d "$LIBDIR" ]; then
    mkdir -p "$LIBDIR"
fi


message 2 "Searching for library dependencies\n"
for file in `find "$TMPDIR/c" -type f -executable -print`; do
    message 5 "scanning executable file for dependencies: $file\n"
    for dep in `ldd $file | sed -e 's@ @\n@g'`; do
        if [ -f "$dep" ]; then
            BASENAME=`basename $dep`
            message 3 "found dependency:      $dep\n"
            if [ ! -f "$LIBDIR/$BASENAME" ]; then
                message 2 "copying dependency:    $dep\n"
                cp -L "$dep" "$LIBDIR/$BASENAME"
                RETVAL=0
            fi
        fi
    done
done


message 2 "Including statically defined libraries\n"
for dep in $INCLUDE_LIBS; do
    if [ -f "$dep" ]; then
        BASENAME=`basename $dep`
        message 3 "found dependency:      $dep\n"
        if [ ! -f "$LIBDIR/$BASENAME" ]; then
            message 2 "copying dependency:    $dep\n"
            cp -L "$dep" "$LIBDIR/$BASENAME"
            RETVAL=0
        fi
    fi
done

exit $RETVAL
