#!/bin/sh

DIRECTORY=$1
SAPPFILE=$2

if [ -z "$SAPPFILE" -o -z "$DIRECTORY" ]; then
    echo "USAGE: [SAPP DIRECTORY] [SAPP FILE]"
    exit 1
fi

if [ ! -d "$DIRECTORY" ]; then
    echo "ERROR: Could not find SAPP directory: $DIRECTORY"
    exit 1
fi

if [ ! -x "$DIRECTORY/run" ]; then
    echo "ERROR: Directory is not correct format: $DIRECTORY"
    exit 1
fi

if [ ! -d "$DIRECTORY" ]; then
    if ! mkdir -p "$DIRECTORY"; then
        echo "ERROR: Could not create target directory: $DIRECTORY"
        exit 1
    fi
fi


check_valid() {
    STRING=$1
    PATTERN=$2
    case $STRING in
        $PATTERN)
            true
        ;;
        *)
            echo "bad"
            return 1
        ;;
    esac
    return 0
}


# TODO Check for root here...


# Create SAPP file header
echo "#!/bin/env singularity" > $SAPPFILE
echo "PAYLOAD=7" >> $SAPPFILE
echo "DATE='`date +%Y.%m.%d`'" >> $SAPPFILE
echo "USER='`id -un`'" >> $SAPPFILE
echo "BUILDHOST='`hostname`'" >> $SAPPFILE
if [ -f "/etc/redhat-release" ]; then
    echo "OSVERSION='`cat /etc/redhat-release`'" >> $SAPPFILE
elif [ -f "/etc/debian-release" ]; then
    echo "OSVERSION='`cat /etc/debian-release`'" >> $SAPPFILE
fi

(cd $DIRECTORY; find . | cpio -o --quiet -H newc ) | gzip -c9 >> $SAPPFILE

exit 0
