#!/bin/sh

SAPPFILE=$1

if [ -z "$SAPPFILE" ]; then
    echo "USAGE: [SAPP FILE]"
    exit 1
fi

if [ ! -f "$SAPPFILE" ]; then
    echo "ERROR: Could not find SAPP file: $SAPPFILE"
    exit 1
fi

check_valid() {
    STRING=$1
    PATTERN=$2
    case $STRING in
        $PATTERN)
            true
        ;;
        *)
            echo "bad"
            return 1
        ;;
    esac
    return 0
}


# TODO Check for root here...


# Check for SAPP file header

if head -n 1 "$SAPPFILE" | grep -q "^#!/"; then
    PAYLOAD=`head -n 2 "$SAPPFILE" | grep "^PAYLOAD=" | sed -e 's@^PAYLOAD=@@'`
    if [ -z "$PAYLOAD" ]; then
        # Assume the header is at least as long as the intrepter
        PAYLOAD=2
    else
        if ! check_valid "$PAYLOAD" "[0-9]*"; then
            echo "ERROR: Header Length read is not numeric."
            exit 1
        fi
    fi
fi


if [ -n "$PAYLOAD" ]; then
    PAYLOAD=`expr $PAYLOAD - 3`
    tail -n +3 $SAPPFILE | head -n "$PAYLOAD"
else
    echo "No header in $SAPPFILE"
fi
