#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPFILE" ]; then
    message 1 "SAPP output file not passed"
    exit 1
fi

if [ -z "$SAPPDIR" ]; then
    message 1 "SAPPDIR not given"
    exit 1
fi

message 2 "Checking for cached singularity SAPP environment"
if [ -x "$SAPPDIR/singularity" ]; then
    message 2 "Using Cached environment"
else
    message 2 "No singularity cached"
    stdbuf -i0 -o0 head -n 10 "$SAPPFILE" | while read i; do
        if check_pattern "#!/*" "$i"; then
            HEADER=3
        elif [ -z "$NOTFIRST" ]; then
            exit 0
        elif check_pattern "$HEADER_END" "$i"; then
            exit $HEADER
        elif [ -n "$HEADER" ]; then
            HEADER=`expr $HEADER + 1`
        fi
        NOTFIRST=1
    done
    PAYLOAD_START="$?"

    if [ "$PAYLOAD_START" -gt 10 ]; then
        message 0 "ERROR: Could not find end of SAPP header"
        exit 1
    fi
    message 3 "SAPP payload starts at $PAYLOAD_START"

    message 2 "Caching SAPP archive"
    tail -n "+$PAYLOAD_START" "$SAPPFILE" | gunzip -dc | (cd "$SAPPDIR"; cpio -id --quiet)
fi


exit 0
