#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPSPEC" ]; then
    message 1 "SAPP specfile not given"
    exit 1
fi

if [ -z "$TMPDIR" ]; then
    message 1 "TMPDIR not given"
    exit 1
fi




for i in `get_key_from_conf "Files" $SAPPSPEC`; do
    copy_file_to_sappdir "$i" "$TMPDIR"
done

copy_file_to_sappdir "/bin/sh" "$TMPDIR"

echo "#!/bin/sh" > $TMPDIR/singularity
get_key_from_conf "script" $SAPPSPEC >> $TMPDIR/singularity
if [ "$?" -ne 0 ]; then
    message 2 "generating a basic singularity runscript"
    echo "exec $runprog \"$@\"" >> $TMPDIR/singularity
fi
chmod 755 $TMPDIR/singularity

exit 0
