#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi

if [ -z "$SAPPSPEC" ]; then
    message 0 "ERROR: SAPP specfile not given\n"
    exit 1
fi

if [ -z "$TMPDIR" ]; then
    message 0 "ERROR: TMPDIR not given\n"
    exit 1
fi



if [ ! -d "$TMPDIR/c/etc" ]; then
    if ! mkdir -p "$TMPDIR/c/etc" 2>/dev/null; then
        message 0 "ERROR: Could not create directory $TMPDIR/c/etc\n"
    fi
fi


message 3 "Creating template files\n"
cat <<EOF > "$TMPDIR/c/etc/nsswitch.conf"
passwd:     files sss
shadow:     files sss
group:      files sss
hosts:      files dns myhostname
EOF
cat <<EOF > "$TMPDIR/c/etc/resolv.conf"
nameserver 8.8.8.8
EOF
cat <<EOF > "$TMPDIR/c/etc/hosts"
127.0.0.1 localhost
EOF


exit 0
