BootStrap: zypper
OSVersion: 15.3
MirrorURL: http://download.opensuse.org/ports/aarch64/distribution/leap/%{OSVERSION}/repo/oss/
Include: zypper

%runscript
    echo "This is what happens when you run the container..."


%post
    echo "Hello from inside the container"
