BootStrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/altarch/%{OSVERSION}/os/aarch64/
Include: yum

%runscript
    echo "This is what happens when you run the container..."


%post
    echo "Hello from inside the container"
    yum -y install vim-minimal
