#!/bin/sh
# 
# Copyright (c) 2015, Gregory M. Kurtzer
# All rights reserved.
# 
# Copyright (c) 2015, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of
# any required approvals from the U.S. Dept. of Energy).
# All rights reserved.
# 
# 

if [ -z "$libexecdir" ]; then
    echo "Could not identify the Singularity libexecdir."
    exit 1
fi

if [ -f "$libexecdir/singularity/functions" ]; then
    . "$libexecdir/singularity/functions"
else
    echo "Error loading functions: $libexecdir/singularity/functions"
    exit 1
fi


COMMAND="$1"
SAPPCACHE="$HOME/.sapp-cache"
RETVAL=0
export SAPPCACHE RETVAL COMMAND
shift

if [ ! -d "$SAPPCACHE" ]; then
    mkdir -p "$SAPPCACHE"
fi

if [ -z "$COMMAND" ]; then
    message 0 "USAGE: singularity (options) cache [cache command] (cache options)\n"
    exit 1
fi

message 1 "Module is still under development\n"

case "$COMMAND" in
    list)
        for i in $SAPPCACHE/*/*/c/singularity; do
            if [ -f "$i" ]; then
                CONTAINER=`dirname "$i"`
                CHECKSUMDIR=`dirname "$CONTAINER"`
                SAPPDIR=`dirname "$CHECKSUMDIR"`
                SAPPNAME=`basename "$SAPPDIR"`
                SIZE=`cat $CHECKSUMDIR/size 2>&1 || echo "unknown"`
                if [ -s "$CHECKSUMDIR/pids" ]; then
                    STATE="running"
                else
                    STATE="idle"
                fi
                printf "%-30s %-10s %-8s\n" "$SAPPNAME" "$SIZE" "$STATE"
            fi
        done
    ;;
    show)
    ;;
    clean)
    ;;
    *)
        message 0 "ERROR: Unknown command: $COMMAND\n"
    ;;
esac


exit $RETVAL
