#!/bin/bash
#
# Copyright (c) 2017, SingularityWare, LLC. All rights reserved.
#
# See the COPYRIGHT.md file at the top-level directory of this distribution and at
# https://github.com/singularityware/singularity/blob/master/COPYRIGHT.md.
#
# This file is part of the Singularity Linux container project. It is subject to the license
# terms in the LICENSE.md file found in the top-level directory of this distribution and
# at https://github.com/singularityware/singularity/blob/master/LICENSE.md. No part
# of Singularity, including this file, may be copied, modified, propagated, or distributed
# except according to the terms contained in the LICENSE.md file.
#



##############################################################################
# APPS
##############################################################################


singularity_app_install_get() {
    APPNAME="${1:-}"
    FILE="${2:-}"

    if [ ! -x "$SINGULARITY_libexecdir/singularity/bin/get-section" ]; then
        message ERROR "Could not locate get-section program\n"
        exit 255
    fi

    if [ ! -f "$FILE" ]; then
        message ERROR "File not found ($FILE)\n"
        exit 1
    fi

    # To install application, much change to its base and back so paths are relative
    SECTION="'appinstall ${APPNAME}'"
    printf "cd /scif/apps/${APPNAME}\n"
    eval $SINGULARITY_libexecdir/singularity/bin/get-section "$SECTION" "$FILE"
    return 0
}


singularity_app_save() {
    APPNAME="${1:-}"
    FILE="${2:-}"
    OUTPUT_FILE="${3:-}"

    if [ ! -x "$SINGULARITY_libexecdir/singularity/bin/get-section" ]; then
        message ERROR "Could not locate get-section program\n"
        exit 255
    fi

    if [ ! -f "$FILE" ]; then
        message ERROR "File not found ($FILE)\n"
        exit 1
    fi

    SECTION_FOUND="No"
    while read line
    do
        if [[ "$line" == "%appinstall $APPNAME" ]]; then # start of section
            echo "$line" >> $OUTPUT_FILE
            SECTION_FOUND="Yes"
        elif [[ "$line" == %* ]]; then                   # end of section
            if [[ "$SECTION_FOUND" == "Yes" ]]; then
                return 0
            fi
        else
            if [[ "$SECTION_FOUND" == "Yes" ]]; then
                echo "$line" >> $OUTPUT_FILE             # line in section
            fi
        fi
    done < "$FILE"
    return 0
}


singularity_app_init() {

    APPNAME="${1:-}"
    APPROOT="${2:-}"

    APPBASE="${APPROOT}/scif/apps/${APPNAME}"
    if [ ! -d "${APPBASE}" ]; then
        mkdir -p "${APPBASE}/scif"
        message 2 "Creating ${APPBASE}...\n"
    fi

    APPDATA="${APPROOT}/scif/data/${APPNAME}"
    if [ ! -d "${APPDATA}" ]; then
        mkdir -p ${APPDATA}
        mkdir -p "${APPDATA}/input"
        mkdir -p "${APPDATA}/output"
        message 2 "Creating ${APPDATA}...\n"
    fi

}


